### ISSUE TITLE
Multiple k8s resources that use Tilt-controlled images breaks logging

### ISSUE THREAD

**Issue by samhagan** [windmilleng/tilt#1254]
I have a setup where an image is used for two purposes - (i) standard server via Deployment and (ii) migration via Job. The image is built by tilt and both k8s resources use the same image. Tilt groups both the deployment and job together and then monitors the job, which eventually completes. Below is a simplified example:

Tiltfile
```
k8s_yaml(['deployment.yaml', 'job.yaml'])
docker_build('tilt', '.')
```
Dockerfile
```
FROM nginx:alpine
WORKDIR /
COPY start.sh /start.sh
ENTRYPOINT ["/start.sh"]
CMD ["pod", "nginx", "-g", "daemon off;"]
```

start.sh
```
#!/bin/sh

MODE=$1; shift

if [ "$MODE" = "job" ]; then
    echo "Running job..."
    sleep 10
    echo "Job done"
    exit 0
fi

exec "$@"
```

job.yaml
```
apiVersion: batch/v1
kind: Job
metadata:
  name: tilt-job
spec:
  template:
    spec:
      containers:
      - name: tilt-job
        image: tilt:test
        args: ["job"]
      restartPolicy: Never
  backoffLimit: 0
```

deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tilt
  labels:
    app: tilt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tilt
  template:
    metadata:
      labels:
        app: tilt
    spec:
      containers:
      - name: tilt
        image: tilt:test
        ports:
        - containerPort: 80
```

kubectl log output:
```
kubectl logs tilt-767c9bb6cb-fp4l6
10.1.1.1 - - [06/Mar/2019:17:42:01 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.58.0" "-"
kubectl logs tilt-job-n5txm
Running job...
Job done
```

Tilt
```
  RESOURCE NAME                                                              DEPLOY •    BUILD STATUS •  UPDATED
▶ ● tilt ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ Completed • OK       (1.6s) •   2m ago
  ● (Tiltfile) ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ N/A             •   2m ago
```
Tilt logs output
```
Starting Tilt (v0.7.6-dev, built 2019-03-06)…
[Tiltfile] 2019/03/06 09:41:07 Beginning Tiltfile execution

[Tiltfile] 2019/03/06 09:41:07 Successfully executed Tiltfile


──┤ Building: tilt ├──────────────────────────────────────────────
STEP 1/2 — Building Dockerfile: [docker.io/library/tilt]
  │ Tarring context…
    ╎ Created tarball (size: 6.7 kB)
  │ Building image
    ╎ [1/2] FROM docker.io/library/nginx:alpine
    ╎ [2/2] COPY start.sh /start.sh

STEP 2/2 — Deploying
  │ Parsing Kubernetes config YAML
  │ Applying via kubectl

  │ Step 1 - 1.157s
  │ Step 2 - 0.424s
  │ Done in: 1.581s
```

In my actual setup the results were a bit different initially. I had 4 containers in my job, each of which used a different Tilt-controlled image. In this case, I actually lost resources in the Tilt display as a result of adding them. Splitting the job out to 4 jobs fixed that, but still have the monitoring issue.
