### ISSUE TITLE
Tilt doesn't detect all KIND clusters correctly

### ISSUE THREAD

**Issue by jazzdan** [windmilleng/tilt#1510]
Our [heuristics](https://github.com/windmilleng/tilt/blob/2a7779705d676176a0d8ecc45afb95ceaab04df5/internal/k8s/env.go#L46-L61) for determining what kind of Kubernetes cluster is being used are insufficient for all cases. With KIND you can change the name of the context by invoking `kind create cluster` with the `--name` flag. Then Tilt will assume that you are using a remote cluster when in reality it's a local one.

cc @fentas

**Comment by garethr** [comment]
I just discovered the KIND integration, and then unfortunately ran into the issue described here. I generally use clusters configured using `--name`. Is there a workaround at the moment?

**Comment by garethr** [comment]
From Kinds perspective, the context and the cluster are given the same name. Mainly because Kubernetes clusters don't technically have internal names. eg.

```console
$ kind create cluster --help  | grep name
      --name string     cluster context name (default "kind")
```

This results in the following config:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://localhost:53517
  name: <name>
contexts:
- context:
    cluster: <name>
    user: kubernetes-admin
  name: kubernetes-admin@<name>
current-context: kubernetes-admin@<name>
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

I don't think a perfect solution exists at the moment without upstream changes (for instance allowing tags in the config file.)

1. Heuristics using the "kubernetes-admin@" prefix. The Kind generated names always use that username. Maybe combined with the consistent use of the name? ie.

```
cluster.name == X 
AND contexts[0].context.cluster == X
AND contexts[0].context.user == kubernetes-admin
AND contexts[0].name == kubernetes-admin@X
AND current-context == kubernetes-admin@X
```

The downside being I'm not sure how widely used that combination is outside Kind?

2. Alternatively, triggering based on the name of the cluster having a `kind` prefix or suffix would at least make it possible to use Tilt with non-default named Kind clusters.

It may be worth checking with @BenTheElder if there is another way of detecting a cluster as Kind?
