### ISSUE TITLE
Helmfile support required

### ISSUE THREAD

**Issue by romikoops** [windmilleng/tilt#1517]
Please support https://github.com/roboll/helmfile

It is impossible to use Tilt without this support for my projects.

**Comment by nicks** [comment]
Hi @romikoops ! I don't know much about `helmfile`, but Tilt has a `local` command that lets you shell out to arbitrary commands. 

Here's a very simple example with Helm: https://docs.tilt.dev/helm.html

Looking at the helmfile docs, I think you might be able to do something like

 ```
k8s_yaml(local('helmfile template ...'))
```

to get the yaml from helmfile into Tilt. would that work?

**Comment by romikoops** [comment]
@nicks I will try and leave comment with results soon

**Comment by romikoops** [comment]
@nicks unfortunately the solution does not work. Here is what I have:

# k8s/staging/hemlfile.yaml
```yaml
releases:
  - name: redis
    chart: stable/redis
    values:
      - redis.yml
  - name: postgres
    chart: stable/postgresql
    values:
      - postgres.yml
```
# k8s/staging/postgres.yml
```yaml
existingSecret: postgres-secured-data
resources:
  limits:
    cpu: 0.5
    memory: 512M
  requests:
    cpu: 0
    memory: 128M
```
# k8s/staging/redis.yml
```yaml
master:
  persistence:
    enabled: false
  resources:
    limits:
      cpu: 0.5
      memory: 128M
    requests:
      cpu: 0
      memory: 32M
cluster:
  enabled: false
usePassword: false
```

# Tiltfile
```
k8s_yaml(local("helmfile template k8s/staging/databases/helmfile.yaml"))
```

<img width="1614" alt="Screenshot 2019-04-27 at 20 31 53" src="https://user-images.githubusercontent.com/220115/56853694-8658fd80-692b-11e9-8101-bfe409fbabaf.png">
