### ISSUE TITLE
[docker-compose] Restart containers if a file/folder that is part of volumes has changed

### ISSUE THREAD

**Issue by fkaleo** [windmilleng/tilt#1638]
When using a `docker-compose.yml` that defines a container with volumes, it would be really great if the container was automatically restarted if a file/folder used as source in the volumes section of that container changed.
For example if `mycool_file_or_folder` changes in the following example `docker-compose.yml`, the container should be restarted:
```
version: '2'

services:
  mycontainer:
    image: myimage
    volumes:
      - mycool_file_or_folder:/usr/bin/
```
