### ISSUE TITLE
K8s objects not included in the resources above

### ISSUE THREAD

**Issue by Bram-Zijp** [windmilleng/tilt#1682]
When using Tilt instead of the vanilla way to apply/create your kubernetes files I get errors of K8s objects not being included.

For example `./frontend/configmap.yml`:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
```
 `./frontend/deployment.yml`:
```
...
      env:
        - name: FRONTEND_CONFIG
          valueFrom:
            configMapKeyRef:
              name: frontend-configmap
```

Above example will throw out the following error:
```
     K8s objects not included in the resources above:                                                                                 
      k8sConfigMap-frontend-configmap
```

Is this a bug or can I resolve this by configuration?
