### ISSUE TITLE
Alert appears with no message/context

### ISSUE THREAD

**Issue by jazzdan** [windmilleng/tilt#1769]
Repro steps:
1) Create a dockerfile
```
FROM alpine
```

2) Create a deploy.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: my-app
```

3) Create a Tiltfile
```
k8s_yaml('deploy.yaml')
docker_build('my-app', '.')
```

4) Run `tilt up`

Expected:
The service crashes and tells me why

Actual:
An empty alert box

![Screenshot from 2019-06-24 12-44-10](https://user-images.githubusercontent.com/452453/60046581-bb689e80-9695-11e9-8f2b-5766f2c00127.png)

I also uploaded these repro steps as a branch in the Tilt repo

https://github.com/windmilleng/tilt/tree/nicks/crash/testdata
