### ISSUE TITLE
Unexpected behavior/bug when environment variable value is the same as the container name

### ISSUE THREAD

**Issue by epotex** [windmilleng/tilt#1793]
When an environment variable value is set to be the same as the container name Tilt will inject
 the docker image URI as the value, for example, given the following Tiltfile configuration:

```
docker_build('test', './')
k8s_yaml('deployment.yaml')
```

and  the following deployment yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - env:
        - name: testing
          value: test
        image: test
        name: test
```

the container will end up with the docker image URI as the value for the 'testing' environment variable
```
Environment:
      test:  docker.io/library/test:tilt-9a1508db4f01a598
```
