### ISSUE TITLE
Visibility for jobs

### ISSUE THREAD

**Issue by AleF83** [windmilleng/tilt#1815]
Hi,
I'm adding e2e tests to my project now and It's pretty cool to develop with Tilt.
In my Tiltfile I run some deployments and then run job with e2e tests.
All works perfect.
The only thing I don't get the indication in UI that tests pass or failed.
The job completes but in UI there is green light like for running pod.
The only way is to read logs (in UI).
It will be cool to add more visibility for jobs. (maybe green V or red X)

The job file: 

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: e2e
  namespace: agogos
  labels:
    name: e2e
    app: e2e
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: e2e
        image: e2e
        imagePullPolicy: Never
  backoffLimit: 0

```

Thank you

**Comment by jazzdan** [comment]
Thanks for the report @AleF83! This is something we've thought about, and it's [on our roadmap](https://github.com/windmilleng/tilt/blob/master/ROADMAP.md#unit-tests). Will update here when we have something in the works

**Comment by andymartin-sch** [comment]
being able to differentiate between `Running` and `Completed` from the "Sidebar UI" alone would be nice

**Comment by inech** [comment]
I've managed to achieve the desired behavior by adding a never succeeding readiness prob to my job.

```yaml
          readinessProbe:
            exec:
              command:
              - "exit"
              - "1"
            initialDelaySeconds: 999999
```

With this hack, the job is in a "pending" state until it finishes with success or failure. It also means that now it's possible to run jobs in a real sequence, starting the next job only when the previous one finishes.

```
k8s_resource('job1')
k8s_resource('job2', resource_deps=['job1'])
```
