### ISSUE TITLE
Tilt failed to create namespace

### ISSUE THREAD

**Issue by AleF83** [windmilleng/tilt#1853]
I have yaml file that creates namespace:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: agogos
  labels:
    name: agogos
```

When I run tilt I get the following:

```
k8s.NewTarget: unable to find a unique resource name for 'agogos:namespace:default:'
```

Tilt version is `v0.9.3, built 2019-07-11`.

I think it may be caused by empty `Group` property of namespace object here:
https://github.com/windmilleng/tilt/blob/fc1b9ef4304ec8fce9cc79f01ae2e1275a9399db/internal/k8s/names.go#L44

Thanks,
Alex
