### ISSUE TITLE
Consider exposing a list of resources Tilt "knows about" and their statuses

### ISSUE THREAD

**Issue by hausdorff** [windmilleng/tilt#1899]
I have YAML like the below. It is a bit hard for me to tell using only the web UI sidebar the status of each of these.

Also nice would be to expose the environment you deployed to.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexbot
  labels:
    app: alexbot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alexbot
  template:
    metadata:
      labels:
        app: alexbot
    spec:
      containers:
      - name: alexbot
        image: hausdorff/alexbot
        env:
          - name: SLACK_SIGNING_SECRET
            valueFrom:
              secretKeyRef:
                name: slack
                key: signing-secret
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Secret
metadata:
  name: slack
type: Opaque
data:
  signing-secret: <this is supposed to secret>
---
apiVersion: v1
kind: Service
metadata:
  name: alexbot
spec:
  type: LoadBalancer
  selector:
    app: alexbot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000

```
