### ISSUE TITLE
k8s_kind image_json_path argument erroring on imagenames containing colons (image with tag)

### ISSUE THREAD

**Issue by tamer-hassan** [windmilleng/tilt#1903]
for example, while trying to integrate with KubeDB custom PostgresVersion

```
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: postgis-2.5.2
spec:
  version: 9.6
  db:
    image: "localhost:32001/postgres:postgis-2.5.2"
  exporter:
    image: "kubedb/postgres_exporter:v0.4.7"
  tools:
    image: "kubedb/postgres-tools:9.6-v3"
```

The image name is mistakenly determined as "postgis-2.5.2" instead of "postgres:postgis-2.5.2"

**Comment by landism** [comment]
Sorry you've run into trouble with this!

I suspect our expectations of how people would use this aren't quite matching what you're doing. Can you explain what you're trying to do - how you observed that the image name is determined as "postgis-2.5.2", and why you want it to be determined as "postgres:postgis-2.5.2"?

The behavior I'd expect is:
Tilt determines the image name is `localhost:32001/postgres`, and, if you specify a `docker_build('localhost:32001/postgres`)`, that docker build would have its image inserted into this yaml with a tilt tag (i.e., `kubectl get postgis-2.5.2` would show the image as something like `localhost:32001/postgres:tilt-bdb87344c22c60b5`, which had just been built by tilt).

I think I've confirmed this is behaving as expected in a little Tiltfile [here](https://github.com/windmilleng/servantes/blob/matt/1903/Tiltfile)

**Comment by tamer-hassan** [comment]
Some background info:
0. I needed to run KubeDB with custom Postgres (to include Postgis extension)
1. I already have defined CRD yamls for PostgresVersion & Postgres, since I needed Postgres 9.6 + Postgis 2.5.2 together, per this doc: https://kubedb.com/docs/0.12.0/guides/postgres/custom-versions/setup/
2. Pushing built image to kind-local registry, based on https://github.com/windmilleng/kind-local
so Tiltfile begins with something like:
```
docker_build('localhost:32001/postgres:postgis-2.5.2', './kubedb/postgres',
  dockerfile='./kubedb/postgres/Dockerfile')
```

An example postgresversion.yaml (per the postgres/custom-versions/setup doc linked above)
```
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: postgis-2.5.2
spec:
  version: 9.6
  db:
    image: "localhost:32001/postgres:postgis-2.5.2"
  exporter:
    image: "kubedb/postgres_exporter:v0.4.7"
  tools:
    image: "kubedb/postgres-tools:9.6-v3"
```
