### ISSUE TITLE
Race condition when applying CRDs

### ISSUE THREAD

**Issue by liztio** [windmilleng/tilt#1931]
Repository: https://github.com/kubernetes-sigs/cluster-api-provider-docker
Tiltfile: 
```
project = str(local('gcloud config get-value project')).strip()

k8s_yaml(local('capdctl platform -capd-image gcr.io/' + project + '/capd-manager'))

k8s_yaml('/tmp/everfree.yaml')

custom_build(
  'gcr.io/' + project +'/capd-manager',
  'go build ./cmd/capd-manager && docker build -t $EXPECTED_REF .',
  ['.'],
  ignore='capd-manager',
)
```

Everfree.yaml:
```yaml
---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Cluster
metadata:
  name: vanhoover
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.96.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
---
apiVersion: v1
kind: Pod
metadata:
  name: twocontainers
spec:
  containers:
  - name: sise
    image: mhausenblas/simpleservice:0.5.0
    ports:
    - containerPort: 9876
  - name: shell
    image: centos:7
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
---
apiVersion: v1
kind: Pod
metadata:
  name: onecontainer
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: false
    kind: Pod
    name: twocontainers
    uid: b1dd6dc3-ae50-11e9-9530-0242ac110005
spec:
  containers:
  - name: shell
    image: centos:7
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: vanhoover-controlplane-0
  labels:
    cluster.k8s.io/cluster-name: vanhoover
    set: controlplane
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: false
    kind: Pod
    name: twocontainers
    uid: b1dd6dc3-ae50-11e9-9530-0242ac110005
spec:
  versions:
    kubelet: v1.14.4
    controlPlane: v1.14.4
  providerSpec: {}  
```

Leads me to an error:

```
ERROR: kubectl apply:
stderr: unable to recognize "STDIN": no matches for kind "Cluster" in version "cluster.k8s.io/v1alpha1"
unable to recognize "STDIN": no matches for kind "Machine" in version "cluster.k8s.io/v1alpha1"
: exit status 1
```
