### ISSUE TITLE
finding images in ... invalid reference format

### ISSUE THREAD

**Issue by zkutasi** [windmilleng/tilt#2969]
Hi,

I am currently working on a company project and would like to advocate to use Tilt as it is a cool tool.

Today I have updated one of the Helm Charts in my umbrella Chart (which dependency we have no control over, we handle the umbrella only), and this is the error I get: 
Please understand that I had to redact any sensitive information...

`finding images in k8sjobname: parsing REPOURL"/"PROJ/IMAGE":"TAG: invalid reference format`

The issue is with the quotation marks around the slash (/) and the colon (:), Helm has no trouble with these, but Tilt spits an error. Unfortunately someone introduced these into a templated Job description, and it is not a good answer that "because Tilt does not like this, do not do it".

In the template, it is like this:

`image: {{ .Values.X }}"/"{{ .Values.Y }}/{{ .Values.Z }}":"{{ .Values.W }}`

Can I do something about this in my Tiltfile, or can you quick-fix this?

**Comment by nicks** [comment]
Hmmm...as far as I can tell, Kubernetes blows up if you give it an image with quotes in the name. Example:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe
  labels:
    app: fe
spec:
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
      - name: fe
        image: busybox":"latest
```

gives me:

```
Warning  InspectFailed  5s (x4 over 34s)  kubelet, dopey     Failed to apply default image tag "busybox\":\"latest": couldn't parse image reference "busybox\":\"latest": invalid reference format
```

when I describe the pod. Am I missing something?
