### ISSUE TITLE
get minikube ip correctly with non-default-name clusters (was: Issue to detect local cluster on minikube)

### ISSUE THREAD

**Issue by DblK** [windmilleng/tilt#3062]
Hi,

I saw the [FAQ](https://docs.tilt.dev/faq.html#q-im-getting-push-errors-like-unauthorized-you-dont-have-the-needed-permissions-what-do-i-do) about the issue I encounter today about trying to push to a registry on a local cluster.

Everything was working fine with minikube locally until I changed the name of the project used by minikube to allow me to have two distinct clusters for dev purpose.
Launching minikube with `minikube -p anothercluster` let `tilt` considers this as a remote cluster instead of local one.

As I watch the source [code](https://github.com/windmilleng/tilt/blob/5c73343289128a11046358ec23135f2b6f6a53fa/internal/k8s/env.go#L66) I saw that we have few cases to find out if it's a local or a remote cluster.

Would it be possible to provide a command to tilt to manually specify a local cluster based on the name of the context?

This will solve my issue and allow user to run the local kubernetes cluster where and which the tool they want (maybe k3os on virtualbox or kvm).

Suggestions:
- `tilt set localenv my-context` ==> Set a specific k8s context to be a local one (ignoring push)
- `tilt get localenv`/`tilt ls localenv` => Get/List localenv

or in another way:
- `tilt local set my-context`
- `tilt local ps`/ `tilt local get`/ `tilt local ls`

Pick the ones you find the best ;)

**Comment by maiamcc** [comment]
Thanks for opening an issue! The short-term workaround for you is to make sure your cluster name [has the prefix `minikube`](https://github.com/windmilleng/tilt/blob/5c73343289128a11046358ec23135f2b6f6a53fa/internal/k8s/env.go#L78), e.g. "minikube-anothercluster". Will this work for you for now?

As for being able to manually tell Tilt whether your cluster is local--agree, this would be a great feature! I think #3024 covers that request, do you agree? If so I'll close this issue in favor of that one, and track your request there.

**Comment by DblK** [comment]
Thank for the fast answer! Renaming the cluster name did not the trick.
Tilt showed me:
```bash
Error: Refusing to run 'local' because minikube-xxx might be a production kube context.
If you're sure you want to continue add:
allow_k8s_contexts('minikube-xxx')
before this function call in your Tiltfile. Otherwise, switch k8s contexts and restart Tilt.
```
So I did add the line `allow_k8s_contexts('minikube-xxx')` as first line of my tiltfile, but still get the error.
I am using tilt version 0.12.5, so I will test again with latest (0.12.7) and add another comment

You can close this issue (once my issue solved), but I would like to see my examples/suggestions to be mentioned in #3024 to provide another way to solve the current issue.

Anyway, thanks for you product. I love it!

**Comment by maiamcc** [comment]
Haha yeah the commit with cluster-detection-by-prefix went out in [v0.12.6](https://github.com/windmilleng/tilt/releases/tag/v0.12.6) -- so try upgrading to the latest Tilt and trying again? Look forward to hearing what happens.

**Comment by DblK** [comment]
I just tested with `0.12.7` but it still does work. I cannot launch tilt now.
After some digging, it seems [that](https://github.com/windmilleng/tilt/blob/1b0d5c30e9bd0fa81226c10d88adcad2c9e87655/internal/k8s/ip.go#L33) is causing the issue. 
The command issued is `minikube ip` and in my case it should be `minikube ip -p minikube-xxx`.
The former does not show anything whereas the later does the trick.

In addition to this reporting, why to you retrieve the ip that way? Wouldn't it be possible to use the k8s config to read the ip from the yaml `~/.kube/config` file?
If you do that way, it will work with anything even other way to deploy the cluster.

**Comment by DblK** [comment]
I just found a temporary workaround by launching `minikube profile minikube-xxx`.
This allows `minikube ip` to return the right value without specifying the profile.

**Comment by maiamcc** [comment]
Glad you found a workaround, and good catch with the `minikube ip` call.

I don't think it would be tooooo hard to pipe the cluster name through so that we could pass it to the `minikube ip` call, I can look into this later.

> Wouldn't it be possible to use the k8s config to read the ip from the yaml ~/.kube/config file?
@nicks can you speak to this?

**Comment by nicks** [comment]
I don't think it's that simple.

Here's the implementation of `minikube ip`: https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/ip.go

It might be worth filing a support request upstream with minikube to ask what kind of API guarantees they're willing to support re: tooling auto-inferring the minikube configuration params

**Comment by DblK** [comment]
So, what I had in mind talking about the ip through the kube config is based on [this documentation](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/).

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority: fake-ca-file
    server: https://1.2.3.4
  name: development
- cluster:
    insecure-skip-tls-verify: true
    server: https://5.6.7.8
  name: scratch
contexts:
- context:
    cluster: development
    namespace: frontend
    user: developer
  name: dev-frontend
- context:
    cluster: development
    namespace: storage
    user: developer
  name: dev-storage
- context:
    cluster: scratch
    namespace: default
    user: experimenter
  name: exp-scratch
current-context: "scratch"
kind: Config
preferences: {}
users:
- name: developer
  user:
    client-certificate: fake-cert-file
    client-key: fake-key-file
- name: experimenter
  user:
    password: some-password
    username: exp
```
Based on the `current-context` or by the `allow_k8s_contexts` tilt command, you can deduce from this yaml the ip you need to work onto.
Here, the `current-context` is `scratch` so we look into this part:

```yaml
- cluster:
    insecure-skip-tls-verify: true
    server: https://5.6.7.8
  name: scratch
```

And from the `server` property, you know that the ip is `5.6.7.8`.
The same work if I specify the `development` context which has the ip `1.2.3.4`.

I hope my explanation are clear enough.
