### ISSUE TITLE
applying v1beta1 StatefulSet fails with label selector problems

### ISSUE THREAD

**Issue by nicks** [windmilleng/tilt#3111]
Repro steps:
1) Create a Tiltfile with the following yaml

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: tilt-site
spec:
  template:
    metadata:
      labels:
        app: tilt-site
    spec:
      containers:
      - name: tilt-site
        image: tilt-site
        ports:
        - containerPort: 4000
          name: http
```

2) Run `tilt up`
3) Modify the source code in the image
4) Run `tilt up` again

Result:
Tilt will fail with an error that looks like this:

>  The StatefulSet "tilt-site" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"tilt-site", "app.kubernetes.io/managed-by":"tilt", "tilt.dev/pod-template-hash":"89cdd3640afdb1b26db7"}: `selector` does not match template `labels`

See this snapshot
https://cloud.tilt.dev/snapshot/Acjq0-cL9zDD3ye6LlA=

The background here is that v1beta1 StatefulSets make the Selector required. v1 Statefulsets make the Selector optional. Internally, Kubernetes promotes a v1beta1 StatefulSet to a v1 StatefulSet. It does this by guesstimating what the Selector should be.

Tilt applies labels to help identify workloads. When it does this, Kubernetes adds these labels to the selector. But sometimes these labels change. This breaks Kubernetes because it can't change the selector.

In the short term, users can work around this by ensuring all StatefulSets have a Selector.

We can also hack around this on the Tilt side, in the same way we hacked around it for v1beta1 Deployments.
